/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assertiontest;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testSum() {
        var expected = 5;
        var actual = App.sum(3, 2);
        assertEquals(expected, actual);
    }
}
